//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun_tbl
    {
        public int UrunID { get; set; }
        public string urun_adi { get; set; }
        public string urun_aciklama { get; set; }
        public Nullable<decimal> urun_fiyat { get; set; }
        public Nullable<int> stok { get; set; }
    }
}
